create table Customers (
	customer_id INT,
	first_name VARCHAR(50),
	last_name VARCHAR(50),
	address VARCHAR(50),
	city VARCHAR(50),
	state VARCHAR(50),
	phone_number VARCHAR(50),
	email VARCHAR(50)
);
insert into Customers (customer_id, first_name, last_name, address, city, state, phone_number, email) values (1, 'Siobhan', 'Darbon', 'Apt 1269', 'Mionica', null, '679-692-5677', 'sdarbon0@a8.net');
insert into Customers (customer_id, first_name, last_name, address, city, state, phone_number, email) values (2, 'Port', 'L''Hommeau', 'Room 1942', 'Priyutovo', null, '752-482-1466', 'plhommeau1@flavors.me');
insert into Customers (customer_id, first_name, last_name, address, city, state, phone_number, email) values (3, 'Nathanael', 'Elsop', 'PO Box 50423', 'Pithoro', null, '138-257-1467', 'nelsop2@slate.com');
insert into Customers (customer_id, first_name, last_name, address, city, state, phone_number, email) values (4, 'Sheila', 'Dabernott', 'Apt 30', 'Batuidu', null, '620-354-4238', 'sdabernott3@ucoz.ru');
insert into Customers (customer_id, first_name, last_name, address, city, state, phone_number, email) values (5, 'Kristen', 'Stockle', 'Apt 71', 'Xinmin', null, '692-264-3328', 'kstockle4@joomla.org');
insert into Customers (customer_id, first_name, last_name, address, city, state, phone_number, email) values (6, 'Charleen', 'Birtchnell', 'Room 1966', 'Havtsal', null, '855-963-3920', 'cbirtchnell5@fastcompany.com');
insert into Customers (customer_id, first_name, last_name, address, city, state, phone_number, email) values (7, 'Rolph', 'Van Merwe', 'Suite 48', 'Baytā al Fawqā', null, '787-417-3544', 'rvanmerwe6@mtv.com');
insert into Customers (customer_id, first_name, last_name, address, city, state, phone_number, email) values (8, 'Denna', 'Goodings', 'Suite 10', 'Lebedyn', null, '314-546-3034', 'dgoodings7@ask.com');
insert into Customers (customer_id, first_name, last_name, address, city, state, phone_number, email) values (9, 'Ashla', 'Doblin', '6th Floor', 'Pataypampa', null, '280-379-4813', 'adoblin8@scientificamerican.com');
insert into Customers (customer_id, first_name, last_name, address, city, state, phone_number, email) values (10, 'Kirby', 'Burbage', 'Suite 8', 'Arys', null, '646-118-9198', 'kburbage9@prnewswire.com');
insert into Customers (customer_id, first_name, last_name, address, city, state, phone_number, email) values (11, 'Tobe', 'Whithorn', 'Suite 22', 'Karanggeneng', null, '340-760-6221', 'twhithorna@hostgator.com');
insert into Customers (customer_id, first_name, last_name, address, city, state, phone_number, email) values (12, 'Herbie', 'Coch', 'Room 1748', 'Zastávka', null, '348-520-2065', 'hcochb@indiegogo.com');
insert into Customers (customer_id, first_name, last_name, address, city, state, phone_number, email) values (13, 'Dorey', 'Going', 'PO Box 66683', 'Bhola', null, '740-288-6725', 'dgoingc@yolasite.com');
insert into Customers (customer_id, first_name, last_name, address, city, state, phone_number, email) values (14, 'Godiva', 'Matthai', '13th Floor', 'Paranavaí', null, '130-789-2003', 'gmatthaid@nyu.edu');
insert into Customers (customer_id, first_name, last_name, address, city, state, phone_number, email) values (15, 'Latrina', 'Ferriman', 'Room 263', 'Japerejo', null, '916-933-5137', 'lferrimane@vk.com');
insert into Customers (customer_id, first_name, last_name, address, city, state, phone_number, email) values (16, 'Cherilynn', 'Pickwell', '5th Floor', 'Parbatipur', null, '694-675-7881', 'cpickwellf@intel.com');
insert into Customers (customer_id, first_name, last_name, address, city, state, phone_number, email) values (17, 'Lockwood', 'Sherme', 'Room 15', 'Situbondo', null, '876-928-0261', 'lshermeg@washingtonpost.com');
insert into Customers (customer_id, first_name, last_name, address, city, state, phone_number, email) values (18, 'Normie', 'Emeney', 'Apt 1876', 'Taoyuan', null, '290-721-9666', 'nemeneyh@washington.edu');
insert into Customers (customer_id, first_name, last_name, address, city, state, phone_number, email) values (19, 'Jeffrey', 'Dovington', 'Suite 100', 'Sovetsk', null, '341-353-5403', 'jdovingtoni@slate.com');
insert into Customers (customer_id, first_name, last_name, address, city, state, phone_number, email) values (20, 'Maynard', 'Colcomb', 'Apt 1333', 'Arneiro', 'Lisboa', '599-498-9062', 'mcolcombj@cornell.edu');
insert into Customers (customer_id, first_name, last_name, address, city, state, phone_number, email) values (21, 'Ellie', 'Sherratt', 'PO Box 26507', 'Karpushikha', null, '897-390-8741', 'esherrattk@nydailynews.com');
insert into Customers (customer_id, first_name, last_name, address, city, state, phone_number, email) values (22, 'Bentlee', 'Butterick', 'Suite 64', 'Čelopek', null, '450-139-7052', 'bbutterickl@seesaa.net');
insert into Customers (customer_id, first_name, last_name, address, city, state, phone_number, email) values (23, 'Francine', 'O''Nion', 'Suite 91', 'Luklukan', null, '890-249-8469', 'fonionm@taobao.com');
insert into Customers (customer_id, first_name, last_name, address, city, state, phone_number, email) values (24, 'Randolph', 'Bowery', 'PO Box 52708', 'Georgīevka', null, '451-264-9055', 'rboweryn@reference.com');
insert into Customers (customer_id, first_name, last_name, address, city, state, phone_number, email) values (25, 'Parnell', 'Tomaszek', 'Suite 33', 'Pila', null, '105-680-6793', 'ptomaszeko@hostgator.com');
insert into Customers (customer_id, first_name, last_name, address, city, state, phone_number, email) values (26, 'Neal', 'Bowick', '10th Floor', 'Nakuru', null, '482-372-6665', 'nbowickp@independent.co.uk');
insert into Customers (customer_id, first_name, last_name, address, city, state, phone_number, email) values (27, 'Randell', 'Vercruysse', 'Room 1785', 'Gostagayevskaya', null, '382-109-4414', 'rvercruysseq@cyberchimps.com');
insert into Customers (customer_id, first_name, last_name, address, city, state, phone_number, email) values (28, 'Tova', 'Stein', 'Suite 95', 'Celso Ramos', null, '182-648-8648', 'tsteinr@freewebs.com');
insert into Customers (customer_id, first_name, last_name, address, city, state, phone_number, email) values (29, 'Cyndi', 'Blucher', 'PO Box 41606', 'København', 'Region Hovedstaden', '934-260-6249', 'cbluchers@scientificamerican.com');
insert into Customers (customer_id, first_name, last_name, address, city, state, phone_number, email) values (30, 'Merilyn', 'Martinelli', '18th Floor', 'Hongqi', null, '714-907-1206', 'mmartinellit@nba.com');
insert into Customers (customer_id, first_name, last_name, address, city, state, phone_number, email) values (31, 'Porty', 'Petriello', 'Apt 50', 'Wotan', null, '217-913-6538', 'ppetriellou@theguardian.com');
insert into Customers (customer_id, first_name, last_name, address, city, state, phone_number, email) values (32, 'Jessey', 'Sargant', 'PO Box 32435', 'Tanahmerah', null, '614-911-0250', 'jsargantv@telegraph.co.uk');
insert into Customers (customer_id, first_name, last_name, address, city, state, phone_number, email) values (33, 'Goldy', 'Loughhead', 'Apt 1663', 'Qinxi', null, '668-931-4874', 'gloughheadw@diigo.com');
insert into Customers (customer_id, first_name, last_name, address, city, state, phone_number, email) values (34, 'Graig', 'Magister', 'PO Box 40427', 'Oesena', null, '262-876-7198', 'gmagisterx@indiatimes.com');
insert into Customers (customer_id, first_name, last_name, address, city, state, phone_number, email) values (35, 'Pedro', 'Jakel', 'Apt 88', 'Khok Charoen', null, '496-115-1951', 'pjakely@google.com.au');
insert into Customers (customer_id, first_name, last_name, address, city, state, phone_number, email) values (36, 'Torre', 'Ondracek', 'Suite 75', 'Wielbark', null, '360-648-0520', 'tondracekz@alibaba.com');
insert into Customers (customer_id, first_name, last_name, address, city, state, phone_number, email) values (37, 'Antoni', 'Winwood', 'PO Box 3477', 'Khiv', null, '105-436-3592', 'awinwood10@php.net');
insert into Customers (customer_id, first_name, last_name, address, city, state, phone_number, email) values (38, 'Dewitt', 'Baron', 'PO Box 96461', 'Arroio do Meio', null, '859-219-0890', 'dbaron11@thetimes.co.uk');
insert into Customers (customer_id, first_name, last_name, address, city, state, phone_number, email) values (39, 'Kelvin', 'Yeiles', 'Suite 75', 'Yershov', null, '489-436-3519', 'kyeiles12@wikipedia.org');
insert into Customers (customer_id, first_name, last_name, address, city, state, phone_number, email) values (40, 'Gray', 'Mowatt', 'Room 1523', 'Al Muharraq', null, '233-619-4189', 'gmowatt13@whitehouse.gov');
insert into Customers (customer_id, first_name, last_name, address, city, state, phone_number, email) values (41, 'Cherrita', 'Spruce', 'PO Box 49193', 'Altavista', 'Tamaulipas', '704-659-5583', 'cspruce14@networksolutions.com');
insert into Customers (customer_id, first_name, last_name, address, city, state, phone_number, email) values (42, 'Madison', 'Lovelock', 'Room 1344', 'Tomay Kichwa', null, '888-624-9181', 'mlovelock15@howstuffworks.com');
insert into Customers (customer_id, first_name, last_name, address, city, state, phone_number, email) values (43, 'Arabelle', 'Benny', 'Apt 1852', 'Bahía Honda', null, '985-794-2470', 'abenny16@flickr.com');
insert into Customers (customer_id, first_name, last_name, address, city, state, phone_number, email) values (44, 'Gwennie', 'Inold', '15th Floor', 'Timoulilt', null, '179-256-4042', 'ginold17@fotki.com');
insert into Customers (customer_id, first_name, last_name, address, city, state, phone_number, email) values (45, 'Therese', 'Borkin', '3rd Floor', 'Le Blanc-Mesnil', 'Île-de-France', '895-318-7988', 'tborkin18@opensource.org');
insert into Customers (customer_id, first_name, last_name, address, city, state, phone_number, email) values (46, 'Hart', 'Permain', '11th Floor', 'Chengxi', null, '743-512-1057', 'hpermain19@apache.org');
insert into Customers (customer_id, first_name, last_name, address, city, state, phone_number, email) values (47, 'Leroi', 'Sorensen', 'Room 405', 'Drásov', null, '549-483-6555', 'lsorensen1a@instagram.com');
insert into Customers (customer_id, first_name, last_name, address, city, state, phone_number, email) values (48, 'Iain', 'Week', '1st Floor', 'Soito', 'Viseu', '839-652-0127', 'iweek1b@yahoo.co.jp');
insert into Customers (customer_id, first_name, last_name, address, city, state, phone_number, email) values (49, 'Lindie', 'Agass', 'Apt 231', 'Jincheng', null, '563-880-0779', 'lagass1c@mit.edu');
insert into Customers (customer_id, first_name, last_name, address, city, state, phone_number, email) values (50, 'Lisa', 'Pinckney', 'Apt 506', 'Agrela', 'Braga', '524-403-5553', 'lpinckney1d@youtu.be');
insert into Customers (customer_id, first_name, last_name, address, city, state, phone_number, email) values (51, 'Adelice', 'Gypps', 'Apt 1793', 'Épernay', 'Champagne-Ardenne', '557-816-3403', 'agypps1e@businessweek.com');
insert into Customers (customer_id, first_name, last_name, address, city, state, phone_number, email) values (52, 'Lolita', 'Bourrel', 'Suite 42', 'Xiaojian', null, '256-947-7018', 'lbourrel1f@senate.gov');
insert into Customers (customer_id, first_name, last_name, address, city, state, phone_number, email) values (53, 'Abner', 'Fouracre', '17th Floor', 'Manokwari', null, '166-192-1109', 'afouracre1g@hp.com');
insert into Customers (customer_id, first_name, last_name, address, city, state, phone_number, email) values (54, 'Gideon', 'Bahls', '16th Floor', 'Timba Lauk', null, '485-132-8716', 'gbahls1h@sbwire.com');
insert into Customers (customer_id, first_name, last_name, address, city, state, phone_number, email) values (55, 'Clarence', 'Haswell', 'PO Box 1323', 'Hämeenkoski', null, '989-407-3520', 'chaswell1i@naver.com');
insert into Customers (customer_id, first_name, last_name, address, city, state, phone_number, email) values (56, 'Ruggiero', 'Orr', '14th Floor', 'Wangqinzhuang', null, '586-593-4785', 'rorr1j@posterous.com');
insert into Customers (customer_id, first_name, last_name, address, city, state, phone_number, email) values (57, 'Ethelred', 'Folliott', '14th Floor', 'San Agustin', null, '406-882-1883', 'efolliott1k@redcross.org');
insert into Customers (customer_id, first_name, last_name, address, city, state, phone_number, email) values (58, 'Gabrielle', 'Packman', 'Suite 12', 'Campo Largo', null, '158-356-5221', 'gpackman1l@pen.io');
insert into Customers (customer_id, first_name, last_name, address, city, state, phone_number, email) values (59, 'Lindsey', 'Kewzick', 'PO Box 78016', 'Bao’an', null, '216-657-5608', 'lkewzick1m@surveymonkey.com');
insert into Customers (customer_id, first_name, last_name, address, city, state, phone_number, email) values (60, 'Marybelle', 'Allgood', 'Apt 1117', 'Sapele', null, '636-671-2979', 'mallgood1n@tmall.com');
insert into Customers (customer_id, first_name, last_name, address, city, state, phone_number, email) values (61, 'Brett', 'Adel', 'PO Box 9209', 'Tovarkovskiy', null, '643-970-2658', 'badel1o@noaa.gov');
insert into Customers (customer_id, first_name, last_name, address, city, state, phone_number, email) values (62, 'Manuel', 'Okeshott', 'PO Box 379', 'Tomislavgrad', null, '682-602-6150', 'mokeshott1p@cornell.edu');
insert into Customers (customer_id, first_name, last_name, address, city, state, phone_number, email) values (63, 'Agneta', 'Leaburn', 'Apt 1405', 'Zhongcun', null, '178-701-9773', 'aleaburn1q@about.com');
insert into Customers (customer_id, first_name, last_name, address, city, state, phone_number, email) values (64, 'Corrie', 'Mullard', 'Suite 30', 'Caçador', null, '775-195-4670', 'cmullard1r@usda.gov');
insert into Customers (customer_id, first_name, last_name, address, city, state, phone_number, email) values (65, 'Frederica', 'Francecione', 'PO Box 18708', 'La Laja', null, '901-623-9413', 'ffrancecione1s@altervista.org');
insert into Customers (customer_id, first_name, last_name, address, city, state, phone_number, email) values (66, 'Roderich', 'Sennett', '13th Floor', 'Al Mukallā', null, '795-381-6680', 'rsennett1t@linkedin.com');
insert into Customers (customer_id, first_name, last_name, address, city, state, phone_number, email) values (67, 'Kelley', 'Kilfether', 'PO Box 61428', 'Zhuangtou', null, '108-358-2946', 'kkilfether1u@nytimes.com');
insert into Customers (customer_id, first_name, last_name, address, city, state, phone_number, email) values (68, 'Franchot', 'Daspar', 'Apt 993', 'Baxiangshan', null, '618-923-8933', 'fdaspar1v@fc2.com');
insert into Customers (customer_id, first_name, last_name, address, city, state, phone_number, email) values (69, 'Lexine', 'Thurborn', '12th Floor', 'Liutan', null, '555-997-1445', 'lthurborn1w@sitemeter.com');
insert into Customers (customer_id, first_name, last_name, address, city, state, phone_number, email) values (70, 'Kial', 'Howels', 'Room 54', 'Luohuang', null, '640-923-5194', 'khowels1x@apple.com');
insert into Customers (customer_id, first_name, last_name, address, city, state, phone_number, email) values (71, 'Cleveland', 'Crunkhurn', '8th Floor', 'Lévis', 'Québec', '751-879-4262', 'ccrunkhurn1y@desdev.cn');
insert into Customers (customer_id, first_name, last_name, address, city, state, phone_number, email) values (72, 'Fitz', 'Hinchcliffe', 'Suite 48', 'Devesa', 'Braga', '644-904-6105', 'fhinchcliffe1z@de.vu');
insert into Customers (customer_id, first_name, last_name, address, city, state, phone_number, email) values (73, 'Fernando', 'Wingatt', '6th Floor', 'Hofors', 'Gävleborg', '662-647-4699', 'fwingatt20@wix.com');
insert into Customers (customer_id, first_name, last_name, address, city, state, phone_number, email) values (74, 'Angie', 'Hellyer', '1st Floor', 'Princeton', 'British Columbia', '531-935-4841', 'ahellyer21@linkedin.com');
insert into Customers (customer_id, first_name, last_name, address, city, state, phone_number, email) values (75, 'Hirsch', 'Murthwaite', 'Room 1299', 'Rizal', null, '176-626-3198', 'hmurthwaite22@imgur.com');
insert into Customers (customer_id, first_name, last_name, address, city, state, phone_number, email) values (76, 'Devi', 'Coster', 'Apt 360', 'Shirone', null, '354-725-9257', 'dcoster23@desdev.cn');
insert into Customers (customer_id, first_name, last_name, address, city, state, phone_number, email) values (77, 'Iona', 'Robez', 'Apt 1737', 'Palmas', null, '198-167-9781', 'irobez24@ezinearticles.com');
insert into Customers (customer_id, first_name, last_name, address, city, state, phone_number, email) values (78, 'Felizio', 'Whinray', 'Suite 92', 'Roanoke', 'Virginia', '540-372-9683', 'fwhinray25@nationalgeographic.com');
insert into Customers (customer_id, first_name, last_name, address, city, state, phone_number, email) values (79, 'Anabal', 'Jobern', 'Apt 1346', 'Partesh', null, '971-646-8091', 'ajobern26@google.ru');
insert into Customers (customer_id, first_name, last_name, address, city, state, phone_number, email) values (80, 'Art', 'Honsch', 'Room 1319', 'Höviyn Am', null, '464-627-1630', 'ahonsch27@acquirethisname.com');
insert into Customers (customer_id, first_name, last_name, address, city, state, phone_number, email) values (81, 'Herby', 'Barnett', 'Apt 146', 'Caen', 'Basse-Normandie', '871-806-4225', 'hbarnett28@cnet.com');
insert into Customers (customer_id, first_name, last_name, address, city, state, phone_number, email) values (82, 'Adah', 'Gooderson', 'PO Box 17271', 'Panoongan', null, '401-891-9936', 'agooderson29@xinhuanet.com');
insert into Customers (customer_id, first_name, last_name, address, city, state, phone_number, email) values (83, 'Haily', 'Bohler', '15th Floor', 'Laval', 'Pays de la Loire', '976-772-3622', 'hbohler2a@qq.com');
insert into Customers (customer_id, first_name, last_name, address, city, state, phone_number, email) values (84, 'Alice', 'Fehner', 'Apt 1376', 'Beaverlodge', 'Alberta', '882-579-5788', 'afehner2b@chicagotribune.com');
insert into Customers (customer_id, first_name, last_name, address, city, state, phone_number, email) values (85, 'Atlante', 'Hardes', 'Suite 83', 'Heliconia', null, '594-147-0364', 'ahardes2c@rakuten.co.jp');
insert into Customers (customer_id, first_name, last_name, address, city, state, phone_number, email) values (86, 'Barbi', 'Brick', 'Apt 1262', 'Stavanger', 'Rogaland', '177-295-6654', 'bbrick2d@clickbank.net');
insert into Customers (customer_id, first_name, last_name, address, city, state, phone_number, email) values (87, 'Jena', 'Enrique', 'Room 491', 'Honglai', null, '220-171-2086', 'jenrique2e@ucoz.com');
insert into Customers (customer_id, first_name, last_name, address, city, state, phone_number, email) values (88, 'Austen', 'Felgate', 'Room 1525', 'Bouças', 'Viana do Castelo', '950-538-9381', 'afelgate2f@latimes.com');
insert into Customers (customer_id, first_name, last_name, address, city, state, phone_number, email) values (89, 'Ann', 'Bellhanger', 'Room 98', 'Kamnica', null, '605-663-8876', 'abellhanger2g@reference.com');
insert into Customers (customer_id, first_name, last_name, address, city, state, phone_number, email) values (90, 'Terry', 'Skene', 'PO Box 9635', 'København', 'Region Hovedstaden', '686-672-8964', 'tskene2h@smh.com.au');
insert into Customers (customer_id, first_name, last_name, address, city, state, phone_number, email) values (91, 'Fulvia', 'MacGorman', '12th Floor', 'Fangshan', null, '492-314-1846', 'fmacgorman2i@hostgator.com');
insert into Customers (customer_id, first_name, last_name, address, city, state, phone_number, email) values (92, 'Bradford', 'Housecraft', 'Suite 84', 'Shancheng', null, '350-447-4601', 'bhousecraft2j@drupal.org');
insert into Customers (customer_id, first_name, last_name, address, city, state, phone_number, email) values (93, 'Werner', 'Parlatt', '1st Floor', 'Jianshan', null, '427-946-8569', 'wparlatt2k@businessinsider.com');
insert into Customers (customer_id, first_name, last_name, address, city, state, phone_number, email) values (94, 'Ania', 'Ivory', '18th Floor', 'Malaga', null, '307-491-6065', 'aivory2l@cyberchimps.com');
insert into Customers (customer_id, first_name, last_name, address, city, state, phone_number, email) values (95, 'Sanford', 'Gieves', 'Room 1567', 'Orion', null, '871-360-9211', 'sgieves2m@icq.com');
insert into Customers (customer_id, first_name, last_name, address, city, state, phone_number, email) values (96, 'Annnora', 'Morais', 'PO Box 73181', 'Cahors', 'Midi-Pyrénées', '840-778-7795', 'amorais2n@sakura.ne.jp');
insert into Customers (customer_id, first_name, last_name, address, city, state, phone_number, email) values (97, 'Rosemary', 'Flooks', 'Room 571', 'San Felipe', null, '875-131-0868', 'rflooks2o@walmart.com');
insert into Customers (customer_id, first_name, last_name, address, city, state, phone_number, email) values (98, 'Papageno', 'Daton', '11th Floor', 'Nakhon Pathom', null, '159-523-0726', 'pdaton2p@ebay.co.uk');
insert into Customers (customer_id, first_name, last_name, address, city, state, phone_number, email) values (99, 'Delainey', 'Misson', '16th Floor', 'Calde', 'Viseu', '443-573-3558', 'dmisson2q@tmall.com');